### ISSUE TITLE
Unquoted optional variable reference generates invalid bash

### ISSUE THREAD

**Issue by christhekeele** [astronomer/deploy-action#19]
On this line:

https://github.com/astronomer/deploy-action/blob/9c67ac721da84fbaf04e26c733ea9218a276e5b0/action.yaml#L91

The `${{ inputs.deployment-id }}` term is unquoted. As it is meant to be optional, that meant that the bash expression expands (post-GH-action variable interpolation) into:

```sh
if [[ "false" != false &&  != false ]]; then
```

This is invalid syntax and fails with

```
/home/runner/work/_temp/04f0abde-f9c5-44e7-ba1b-7e59ee4a4c3b.sh: line 10: conditional binary operator expected
```

**Comment by Geoffrey-Schuette-Simpli-Fi** [comment]
Running into this error/issue as well. Looks like @christhekeele nailed the issues and the suggested fix. 

I don't see anything in your ReadMe for a process to contribute to the repo, but I am sure there are plenty of devs that would be happy to open a PR for a hotfix around this. I would be happy to. 

My org has built a process that is a shell of this repo to deploy our processes in CI/CD, but I would like to start moving to something like this. This is the second time we have tried.

**Comment by christhekeele** [comment]
@Geoffrey-Schuette-Simpli-Fi 

FWIW if you need to you can just switch over to always providing a `deployment-id` to avoid this rather than `deployment-name`

**Comment by christhekeele** [comment]
I have created a fork that tries to fix this, but I don't have the means to vigorously test all input permutations, so more people trying it out is better: https://github.com/astronomer/deploy-action/compare/main...christhekeele:astro-deploy-action:add-missing-quoting-to-inputs

**Comment by Geoffrey-Schuette-Simpli-Fi** [comment]
Thank you for the tip @christhekeele . I tried the id and was still getting the same error. I changed it back to our original process for now. I don't want to keep other team members from deploying anything right now.
