### ISSUE TITLE
GitHub Action sends through using the same AstroClient ID

### ISSUE THREAD

**Issue by stuart23** [astronomer/deploy-action#49]
Can we please pass a unique identifier for requests using the Github Action? Even though under the hood it is still the cli, we need to be able to see whether it was deployed using this action or not.

**Comment by sunkickr** [comment]
With CLI v1.28 the client will be "github-action" for any request made through the cli while inside of a github action. The client will be "deploy-action" for any request made with the CLI from within deploy-action v0.7 and above
