### ISSUE TITLE
Node.js 16 actions are deprecated - Update actions to use Node.js 20

### ISSUE THREAD

**Issue by cmarteepants** [astronomer/deploy-action#50]
I created a new project and deployed example dags. Saw the following warning in the github action logs:

[build](https://github.com/cmarteepants/dag-versioning-sandbox/actions/runs/7712542377/job/21020326476)
Node.js 16 actions are deprecated. Please update the following actions to use Node.js 20: actions/checkout@v3. For more information see: https://github.blog/changelog/2023-09-22-github-actions-transitioning-from-node-16-to-node-20/.

**Comment by joeknize-bc** [comment]
I see this is marked as closed since a PR got merged a few weeks ago, but I'm still seeing the original issue. What's the timeline for this being available for use?

**Comment by adriaanbalt** [comment]
I am also still seeing this issue.
