### ISSUE TITLE
Rebase and Merge causes incorrect use of dag only deploy

### ISSUE THREAD

**Issue by collinmcnulty** [astronomer/deploy-action#52]
A user noticed that [git diff --name-only HEAD^..HEAD](https://github.com/astronomer/deploy-action/blob/main/action.yaml#L267C17-L267C49) returns only one change when Rebase and Merge is selected(as shown in below example) as part of PR merge when there is more than 1 commit.

The user reproduced this locally and reported to Astronomer Support. Though there were two commits(first commit: to include folder and latest commit: to dag folder) but only latest commit is returned as the Rebase and merge is used when merging the PR.

It appears that the Astronomer Github Action only works,
- when either Squash and Merge strategy is used when there is more than 1 commit
or 
- When Rebase and merge is used when there is only 1 commit
but it doesn't work if Rebase and merge is used when there is more than 1 commit.

**Comment by dym-ok** [comment]
I can confirm this affects us too, thanks for raising this 🙏🏾

**Comment by sunkickr** [comment]
This is fixed in v0.5
