### ISSUE TITLE
Deprecated actions/checkout@v3 warning

### ISSUE THREAD

**Issue by gasci** [astronomer/deploy-action#56]
```
Node.js 16 actions are deprecated. Please update the following actions to use Node.js 20: actions/checkout@v3. For more information see: https://github.blog/changelog/2023-09-22-github-actions-transitioning-from-node-16-to-node-20/.
```

We are getting the following warning. Please upgrade the checkout version to remove this error.

**Comment by stuart23** [comment]
This has been upggraded: https://github.com/astronomer/deploy-action/blob/main/action.yaml#L87

**Comment by gasci** [comment]
Thank you for the update. When are you going to release v5?

**Comment by sunkickr** [comment]
@gasci we are waiting to hear back from a few testers. You are welcome to use it now
